// Word Bridge — umumiy stillar (glassmorphism, binafsha gradient)
export const S = {
  nav: {
    position: "sticky",
    top: 0,
    zIndex: 50,
    padding: "16px 0",
    backdropFilter: "blur(12px)",
    background: "rgba(118,75,162,0.35)",
  },
  navInner: {
    display: "flex",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  navBtn: {
    padding: "10px 20px",
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,0.25)",
    fontSize: 14,
  },
  page: {
    maxWidth: 720,
    margin: "0 auto",
    padding: "32px 20px 60px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  hero: { textAlign: "center", marginBottom: 32 },
  bookIcon: { fontSize: 56, marginBottom: 12 },
  bigTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 56,
    fontWeight: 700,
    color: "#fff",
    letterSpacing: "-0.02em",
  },
  midTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 36,
    fontWeight: 700,
    color: "#fff",
  },
  heroSub: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 16,
    marginTop: 10,
    maxWidth: 480,
    marginLeft: "auto",
    marginRight: "auto",
  },
  glassCard: {
    width: "100%",
    background: "rgba(255,255,255,0.1)",
    backdropFilter: "blur(16px)",
    border: "1px solid rgba(255,255,255,0.18)",
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
    boxShadow: "0 8px 32px rgba(0,0,0,0.15)",
  },
  cardHeader: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 22,
    fontWeight: 600,
    color: "#fff",
  },
  cardSub: { color: "rgba(255,255,255,0.65)", fontSize: 14, marginTop: 4 },
  inputRow: { display: "flex", gap: 10, marginTop: 14, alignItems: "center" },
  input: {
    flex: 1,
    padding: "12px 16px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.2)",
    background: "rgba(255,255,255,0.08)",
    color: "#fff",
    fontSize: 15,
    fontFamily: "'Inter', sans-serif",
    outline: "none",
  },
  deleteX: {
    width: 38,
    height: 38,
    borderRadius: 12,
    border: "none",
    background: "#ef4444",
    color: "#fff",
    fontSize: 20,
    lineHeight: 1,
  },
  btnRow: { display: "flex", gap: 12, marginTop: 20, flexWrap: "wrap" },
  outlineBtn: {
    padding: "12px 20px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.4)",
    background: "transparent",
    color: "#fff",
    fontSize: 14,
    fontWeight: 500,
    flex: 1,
  },
  solidBtn: {
    padding: "12px 20px",
    borderRadius: 14,
    border: "none",
    background: "#fff",
    color: "#7c3aed",
    fontSize: 14,
    fontWeight: 600,
    flex: 1,
  },
  resultsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    marginTop: 8,
  },
  sectionTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 26,
    fontWeight: 600,
    color: "#fff",
  },
  saveBtn: {
    padding: "10px 18px",
    borderRadius: 14,
    border: "none",
    background: "#10b981",
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
  },
  cardTopRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  cardTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 18,
    fontWeight: 600,
    color: "#fff",
  },
  badge: {
    background: "rgba(255,255,255,0.15)",
    border: "1px solid rgba(255,255,255,0.2)",
    color: "rgba(255,255,255,0.9)",
    padding: "5px 12px",
    borderRadius: 10,
    fontSize: 12,
  },
  sentence: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 16,
    lineHeight: 1.6,
    margin: "14px 0",
  },
  answerRow: { display: "flex", gap: 10 },
  checkBtn: {
    padding: "12px 20px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.5)",
    background: "transparent",
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
  },
  feedback: { marginTop: 12, fontSize: 14, fontWeight: 600 },
  tabRow: {
    display: "flex",
    gap: 8,
    marginBottom: 20,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  tabBtn: {
    padding: "9px 18px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.3)",
    fontSize: 13,
    fontWeight: 500,
  },
  wordEn: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 24,
    fontWeight: 700,
    color: "#fff",
  },
  wordUz: { color: "rgba(255,255,255,0.8)", fontSize: 16, marginTop: 2 },
  smallBadge: {
    display: "inline-block",
    marginTop: 8,
    background: "rgba(255,255,255,0.12)",
    color: "rgba(255,255,255,0.7)",
    padding: "3px 10px",
    borderRadius: 8,
    fontSize: 12,
  },
  iconCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 8,
  },
  learnedBadge: {
    background: "rgba(16,185,129,0.25)",
    border: "1px solid #10b981",
    color: "#34d399",
    padding: "4px 10px",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.2)",
    background: "rgba(255,255,255,0.08)",
    fontSize: 16,
  },
  exerciseBlock: {
    marginTop: 16,
    paddingTop: 16,
    borderTop: "1px solid rgba(255,255,255,0.12)",
  },
  exerciseLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 13,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  statsRow: { display: "flex", gap: 16, width: "100%", marginBottom: 20 },
  statValue: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 40,
    fontWeight: 700,
    margin: "6px 0",
  },
  pctBig: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 44,
    fontWeight: 700,
    color: "#fff",
  },
  progressTrack: {
    marginTop: 16,
    height: 16,
    borderRadius: 10,
    background: "rgba(255,255,255,0.15)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 10,
    background: "linear-gradient(90deg, #1f1147, #000)",
    transition: "width 0.6s ease",
  },
  recentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 0",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
    color: "#fff",
    fontSize: 15,
  },
  spinnerWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: 40,
  },
  spinner: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    border: "4px solid rgba(255,255,255,0.2)",
    borderTopColor: "#fff",
    animation: "spin 0.8s linear infinite",
  },
  toastWrap: {
    position: "fixed",
    bottom: 24,
    right: 24,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    zIndex: 100,
  },
  toast: {
    color: "#fff",
    padding: "12px 20px",
    borderRadius: 14,
    fontSize: 14,
    fontWeight: 500,
    boxShadow: "0 8px 24px rgba(0,0,0,0.25)",
    animation: "toastIn 0.3s ease",
    maxWidth: 320,
  },
};
